<?php
/**
* @var \Ayastr\Wtrade\Block\Index $block
*/
?>

<div class="form-group">
    <form id="add-product" translate="label">
        <?php echo $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="added-from-wtrade" value="1">
        <label>SKU:
            <input id="sku" name="sku" placeholder="Enter SKU">
        </label>
        <label>Amount:
            <input id="qty" name="qty" placeholder="Enter amount">
        </label>
    </form>
    <button id="post-btn">Add to cart</button>
</div>
