<?php
/**
* @var \Magento\Framework\View\Element\Template $block
*/
?>

<div class="form-group">
    <form action="<?= $block->getUrl('*/Cart/AddToCart') ?>">
        <label>SKU:
            <input id="sku" name="sku" placeholder="Enter SKU">
        </label>
        <label>Amount:
            <input id="qty" name="qty" placeholder="Enter amount">
        </label>
        <button type="submit" value="Submit">Add to cart</button>
    </form>
</div>
